---
name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v1
      - uses: wei/curl@master
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
      - uses: montudor/action-zip@v0.1.0
      - run: |
          echo "$OC_KEY" > rds.key
          echo "$OC_CERT" > rds.crt
        shell: bash
        env:
          OC_KEY: ${{secrets.OC_KEY}}
          OC_CERT: ${{secrets.OC_CERT}}
      - name: "Signature code"
        run: |
          curl https://download.owncloud.org/community/owncloud-complete-20200731.zip -o owncloud.zip
          unzip -qq owncloud.zip
          php owncloud/occ integrity:sign-app --privateKey=${PWD}/rds.key --certificate=${PWD}/rds.crt --path="${PWD}/rds"
      - name: "Build & test"
        run: |
          export RELEASE_VERSION=${GITHUB_REF#refs/tags/v}
          sed -i "s;<version>x.x</version>;<version>${RELEASE_VERSION}</version>;g" rds/appinfo/info.xml  
          tar cfvz ${RELEASE_VERSION}.tar.gz rds/*

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            LICENSE.txt
            *.tar.gz
